version: "3.1"

services:
  web:
    container_name: web-nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html:rw
      - ./docker/conf/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - frontend
  php:
    container_name: php7.3-fpm
    image: php:7.3-fpm-alpine3.10
    depends_on:
      - db
    networks:
      - frontend
    volumes:
      - .:/var/www/html:rw
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql57
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_DATABASE: laravel_db
    networks:
      - frontend
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - frontend
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      PMA_HOST: db
    depends_on:
      - php
      - db

networks:
  frontend:
volumes:
  db_data:
